// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: protos/service-combined.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepeatedOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numbers       []float64              `protobuf:"fixed64,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedOperationRequest) Reset() {
	*x = RepeatedOperationRequest{}
	mi := &file_protos_service_combined_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedOperationRequest) ProtoMessage() {}

func (x *RepeatedOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_combined_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedOperationRequest.ProtoReflect.Descriptor instead.
func (*RepeatedOperationRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_combined_proto_rawDescGZIP(), []int{0}
}

func (x *RepeatedOperationRequest) GetNumbers() []float64 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

type OperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstNumber   float64                `protobuf:"fixed64,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber  float64                `protobuf:"fixed64,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_protos_service_combined_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_combined_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_combined_proto_rawDescGZIP(), []int{1}
}

func (x *OperationRequest) GetFirstNumber() float64 {
	if x != nil {
		return x.FirstNumber
	}
	return 0
}

func (x *OperationRequest) GetSecondNumber() float64 {
	if x != nil {
		return x.SecondNumber
	}
	return 0
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_protos_service_combined_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_combined_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_combined_proto_rawDescGZIP(), []int{2}
}

func (x *OperationResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_protos_service_combined_proto protoreflect.FileDescriptor

const file_protos_service_combined_proto_rawDesc = "" +
	"\n" +
	"\x1dprotos/service-combined.proto\x12\x06protos\"4\n" +
	"\x18RepeatedOperationRequest\x12\x18\n" +
	"\anumbers\x18\x01 \x03(\x01R\anumbers\"Z\n" +
	"\x10OperationRequest\x12!\n" +
	"\ffirst_number\x18\x01 \x01(\x01R\vfirstNumber\x12#\n" +
	"\rsecond_number\x18\x02 \x01(\x01R\fsecondNumber\"+\n" +
	"\x11OperationResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result2\x9b\x03\n" +
	"\x0fCombinedCompute\x12Q\n" +
	"\x0eRootMeanSquare\x12 .protos.RepeatedOperationRequest\x1a\x19.protos.OperationResponse\"\x00(\x01\x12P\n" +
	"\rGeometricMean\x12 .protos.RepeatedOperationRequest\x1a\x19.protos.OperationResponse\"\x000\x01\x12J\n" +
	"\rBodyMassIndex\x12\x18.protos.OperationRequest\x1a\x19.protos.OperationResponse\"\x00(\x010\x01\x12G\n" +
	"\x0ePowerLevelDiff\x12\x18.protos.OperationRequest\x1a\x19.protos.OperationResponse\"\x00\x12N\n" +
	"\x15PercentageValueChange\x12\x18.protos.OperationRequest\x1a\x19.protos.OperationResponse\"\x00B;Z9github.com/lubie-koty/rpc-compute-service-combined/protosb\x06proto3"

var (
	file_protos_service_combined_proto_rawDescOnce sync.Once
	file_protos_service_combined_proto_rawDescData []byte
)

func file_protos_service_combined_proto_rawDescGZIP() []byte {
	file_protos_service_combined_proto_rawDescOnce.Do(func() {
		file_protos_service_combined_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_service_combined_proto_rawDesc), len(file_protos_service_combined_proto_rawDesc)))
	})
	return file_protos_service_combined_proto_rawDescData
}

var file_protos_service_combined_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_service_combined_proto_goTypes = []any{
	(*RepeatedOperationRequest)(nil), // 0: protos.RepeatedOperationRequest
	(*OperationRequest)(nil),         // 1: protos.OperationRequest
	(*OperationResponse)(nil),        // 2: protos.OperationResponse
}
var file_protos_service_combined_proto_depIdxs = []int32{
	0, // 0: protos.CombinedCompute.RootMeanSquare:input_type -> protos.RepeatedOperationRequest
	0, // 1: protos.CombinedCompute.GeometricMean:input_type -> protos.RepeatedOperationRequest
	1, // 2: protos.CombinedCompute.BodyMassIndex:input_type -> protos.OperationRequest
	1, // 3: protos.CombinedCompute.PowerLevelDiff:input_type -> protos.OperationRequest
	1, // 4: protos.CombinedCompute.PercentageValueChange:input_type -> protos.OperationRequest
	2, // 5: protos.CombinedCompute.RootMeanSquare:output_type -> protos.OperationResponse
	2, // 6: protos.CombinedCompute.GeometricMean:output_type -> protos.OperationResponse
	2, // 7: protos.CombinedCompute.BodyMassIndex:output_type -> protos.OperationResponse
	2, // 8: protos.CombinedCompute.PowerLevelDiff:output_type -> protos.OperationResponse
	2, // 9: protos.CombinedCompute.PercentageValueChange:output_type -> protos.OperationResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_service_combined_proto_init() }
func file_protos_service_combined_proto_init() {
	if File_protos_service_combined_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_service_combined_proto_rawDesc), len(file_protos_service_combined_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_service_combined_proto_goTypes,
		DependencyIndexes: file_protos_service_combined_proto_depIdxs,
		MessageInfos:      file_protos_service_combined_proto_msgTypes,
	}.Build()
	File_protos_service_combined_proto = out.File
	file_protos_service_combined_proto_goTypes = nil
	file_protos_service_combined_proto_depIdxs = nil
}
